### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jonathanong** [jonathanong/osx-webdev-setup#6]
- [x] shopt -s globstar error - need the latest bash  http://mistermorris.com/blog/get-yourself-globstar-bash-4-for-your-mac-terminal/
- [x] .vimrc
- [x] why is nvm so confusing?
- [x] git config --global push.default simple
- [x] java https://support.apple.com/kb/DL1572?locale=en_US
- [x] git config --global credential.helper osxkeychain
- [x] https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion
- [x] sudo chown -R $USER /usr/local/include
- [x] `ruby` + `gem`

**Comment by jonathanong** [comment]
nvm:
- create a `~/.nvmrc` file with your ideal version
- you bash profile should have `nvm use` so that it uses the first `nvmrc` version it finds

**Comment by jonathanong** [comment]
https://developers.google.com/speed/public-dns/docs/using?hl=en#mac_os

set google as your DNS server
